class MailModel{
  var mailID;
  var addressID;
  var lastAppearedBranch;
  var postManID;
  var sourceBranchID;
  var receivingBranchID;
  var senderID;
  var receiverID;
  var isAssigned;
  var isDelivered;



  MailModel({
    this.mailID,
    this.addressID,
    this.lastAppearedBranch,
    this.postManID,
    this.sourceBranchID,
    this.receivingBranchID,
    this.senderID,
    this.receiverID,
    this.isAssigned,
    this.isDelivered
    });

}


